<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CTSNJY30731" name="Test" tests="4" failures="1" timestamp="18 Aug 2014 18:27:02 GMT" time="68.138" errors="0">
  <testcase name="runTC1" time="32.478" classname="testscripts.scenario1.TC1"/>
  <testcase name="runTC4" time="37.594" classname="testscripts.scenario2.TC4"/>
  <testcase name="runTC2" time="12.772" classname="testscripts.scenario1.TC2"/>
  <testcase name="runTC3" time="30.224" classname="testscripts.scenario1.TC3">
    <failure type="java.lang.AssertionError" message="Login failed for valid user">
      <![CDATA[java.lang.AssertionError: Login failed for valid user
	at supportlibraries.DriverScript.wrapUp(DriverScript.java:452)
	at supportlibraries.DriverScript.driveTestExecution(DriverScript.java:106)
	at testscripts.scenario1.TC3.runTC3(TC3.java:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:744)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- runTC3 -->
</testsuite> <!-- Test -->
